PRODUCT_PACKAGES += \
		BugReportSender \
		ConfigUpdater \
		GoogleBackupTransport \
		GoogleContactsSyncAdapter \
		GoogleExtServices \
		GoogleExtShared \
		GooglePackageInstaller \
		GoogleServicesFramework \
		GoogleTTS \
		NoTouchAuthDelegate \
		SetupWraith \
		PrebuiltGmsCorePano \
		Tubesky \
		Backdrop \
		AndroidMediaShell \
		GamepadPairingService \
		GlobalKeyInterceptor \
		TV \
		Overscan \
		RemoteControlService \
		SecondScreenSetup \
		SecondScreenSetupAuthBridge \
		talkback \
		AtvCustomization \
		LeanbackLauncher \
		LeanbackIme \
		VideosPano \
		Music2Pano \
		CanvasPackageInstaller \
		FuguPairingTutorial \
		PlayGames \
		AtvRemoteService \
		Katniss \
		AtvWidget \
		YouTubeLeanback \
		LandscapeWallpaper \
		WebViewGoogle
